const fs = require('fs')
const Mustache = require('mustache')
const path = require('path')

const template = fs.readFileSync(path.join(__dirname, "Sfz.g4.mustache"))
const view = {}

const rendered = Mustache.render(template, view)
fs.writeFileSync(path.join(__dirname, "Sfz.g4"), rendered)

supportedOpcodes = [
  "#define",
  "#include",
  // "*_mod",
  "amp_keycenter",
  "amp_keytrack",
  "amp_random",
  // "amp_velcurve_N",
  "amp_veltrack",
  // "amp_veltrack_onccN",
  // "amp_veltrack_curveccN",
  "amp_veltrack_random",
  "ampeg_attack",
  // "ampeg_attackccN",
  "ampeg_vel2attack",
  "ampeg_attack_shape",
  "ampeg_decay",
  // "ampeg_decayccN",
  // "ampeg_decay_curveccN",
  "ampeg_vel2decay",
  "ampeg_decay_shape",
  "ampeg_decay_zero",
  "ampeg_delay",
  // "ampeg_delayccN",
  "ampeg_vel2delay",
  "ampeg_dynamic",
  "ampeg_hold",
  // "ampeg_holdccN",
  // "ampeg_hold_curveccN",
  "ampeg_vel2hold",
  "ampeg_release",
  // "ampeg_releaseccN",
  "ampeg_vel2release",
  "ampeg_release_shape",
  "ampeg_release_zero",
  "ampeg_start",
  // "ampeg_startccN",
  // "ampeg_sustain",
  // "ampeg_sustainccN",
  // "ampeg_sustain_curveccN",
  // "ampeg_vel2sustain",
  "amplfo_delay",
  "amplfo_depth",
  // "amplfo_depthccN",
  "amplfo_depthchanaft",
  "amplfo_depthpolyaft",
  "amplfo_fade",
  "amplfo_freq",
  // "amplfo_freqccN",
  "amplfo_freqchanaft",
  "amplfo_freqpolyaft",
  "amplitude",
  // "amplitude_onccN",
  // "amplitude_curveccN",
  // "amplitude_smoothccN",
  "apan_depth",
  // "apan_depth_onccN",
  "apan_dry",
  // "apan_dry_onccN",
  "apan_freq",
  // "apan_freq_onccN",
  "apan_phase",
  // "apan_phase_onccN",
  "apan_waveform",
  "apan_wet",
  // "apan_wet_onccN",
  // "bend_down",
  "bend_smooth",
  "bend_step",
  // "bend_stepdown",
  "bend_stepup",
  "bend_up",
  "bitred",
  // "bitred_onccN",
  // "bitred_curveccN",
  // "bitred_smoothccN",
  // "bitred_stepccN",
  "bus",
  // "bypass_onccN",
  "comp_attack",
  // "comp_gain",
  "comp_ratio",
  "comp_release",
  "comp_stlink",
  "comp_threshold",
  "count",
  "curve_index",
  "cutoff",
  // "cutoff_ccN",
  // "cutoff_curveccN",
  // "cutoff_smoothccN",
  // "cutoff_stepccN",
  "cutoff_chanaft",
  "cutoff_polyaft",
  "cutoff2",
  // "cutoff2_onccN",
  // "cutoff2_curveccN",
  // "cutoff2_smoothccN",
  // "cutoff2_stepccN",
  "decim",
  // "decim_onccN",
  // "decim_curveccN",
  // "decim_smoothccN",
  // "decim_stepccN",
  "default_path",
  "delay",
  // "delay_ccN",
  "delay_beats",
  "delay_cutoff",
  // "delay_cutoff_onccN",
  "delay_damphi",
  // "delay_damphi_onccN",
  "delay_damplo",
  // "delay_damplo_onccN",
  "delay_dry",
  // "delay_dry_onccN",
  "delay_feedback",
  // "delay_feedback_onccN",
  "delay_filter",
  "delay_input",
  // "delay_input_onccN",
  "delay_levelc",
  "delay_levell",
  "delay_levelr",
  "delay_lfofreq",
  // "delay_lfofreq_onccN",
  "delay_moddepth",
  // "delay_moddepth_onccN",
  "delay_mode",
  "delay_panc",
  // "delay_panc_onccN",
  "delay_panl",
  // "delay_panl_onccN",
  "delay_panr",
  // "delay_panr_onccN",
  "delay_random",
  "delay_resonance",
  // "delay_resonance_onccN",
  "delay_samples",
  // "delay_samples_onccN",
  "delay_spread",
  // "delay_spread_onccN",
  // "delay_syncc_onccN",
  // "delay_syncl_onccN",
  // "delay_syncr_onccN",
  "delay_time_tap",
  "delay_timec",
  // "delay_timec_onccN",
  "delay_timel",
  // "delay_timel_onccN",
  "delay_timer",
  // "delay_timer_onccN",
  "delay_wet",
  // "delay_wet_onccN",
  // "direction",
  // "directtomain",
  "disto_depth",
  // "disto_depth_onccN",
  "disto_dry",
  // "disto_dry_onccN",
  "disto_stages",
  "disto_tone",
  // "disto_tone_onccN",
  "disto_wet",
  // "disto_wet_onccN",
  "dsp_order",
  "effect1",
  "effect2",
  "effect3",
  "effect4",
  /*
  "egN_ampeg",
  "egN_amplitude",
  "egN_amplitude_onccX",
  "egN_bitred",
  "egN_bitred_onccX",
  "egN_curveX",
  "egN_cutoff",
  "egN_cutoff_onccX",
  "egN_cutoff2",
  "egN_cutoff2_onccX",
  "egN_decim",
  "egN_decim_onccX",
  "egN_depth_lfoX",
  "egN_depthadd_lfoX",
  "egN_driveshape",
  "egN_driveshape_onccX",
  "egN_eqXbw",
  "egN_eqXbw_onccY",
  "egN_eqXfreq",
  "egN_eqXfreq_onccY",
  // "egN_eqXgain",
  "egN_eqXgain_onccY",
  "egN_freq_lfoX",
  "egN_levelX",
  "egN_levelX_onccY",
  "egN_loop",
  "egN_loop_count",
  "egN_noiselevel",
  "egN_noiselevel_onccX",
  "egN_noisestep",
  "egN_noisestep_onccX",
  "egN_noisetone",
  "egN_noisetone_onccX",
  // "egN_pan",
  "egN_pan_onccX",
  "egN_pan_curve",
  "egN_pan_curveccX",
  "egN_pitch",
  "egN_pitch_onccX",
  "egN_points",
  "egN_rectify",
  "egN_rectify_onccX",
  "egN_resonance",
  "egN_resonance_onccX",
  "egN_resonance2",
  "egN_resonance2_onccX",
  "egN_ringmod",
  "egN_ringmod_onccX",
  "egN_shapeX",
  // "egN_sustain",
  "egN_timeX",
  "egN_timeX_onccY",
  "egN_volume",
  "egN_volume_onccX",
  "egN_width",
  "egN_width_onccX",
  */
  "end",
  /*
  "eqN_bw",
  "eqN_bwccX",
  "eqN_dynamic",
  "eqN_freq",
  "eqN_freqccX",
  "eqN_vel2freq",
  "eqN_gain",
  "eqN_gainccX",
  "eqN_vel2gain",
  "eqN_type",
   */
  "eq_bw",
  // "eq_bw_onccN",
  "eq_freq",
  // "eq_freq_onccN",
  // "eq_gain",
  // "eq_gain_onccN",
  "eq_type",
  "fil2_gain",
  // "fil2_gain_onccN",
  "fil2_keycenter",
  "fil2_keytrack",
  "fil2_type",
  "fil2_veltrack",
  "fil_gain",
  // "fil_gain_onccN",
  "fil_keycenter",
  "fil_keytrack",
  "fil_random",
  "fil_type",
  "fil_veltrack",
  "fileg_attack",
  // "fileg_attack_onccN",
  "fileg_vel2attack",
  "fileg_attack_shape",
  "fileg_decay",
  // "fileg_decay_onccN",
  "fileg_vel2decay",
  "fileg_decay_shape",
  "fileg_decay_zero",
  "fileg_delay",
  // "fileg_delay_onccN",
  "fileg_vel2delay",
  "fileg_depth",
  // "fileg_depth_onccN",
  "fileg_vel2depth",
  "fileg_dynamic",
  "fileg_hold",
  // "fileg_hold_onccN",
  "fileg_vel2hold",
  "fileg_release",
  // "fileg_release_onccN",
  "fileg_vel2release",
  "fileg_release_shape",
  "fileg_release_zero",
  "fileg_start",
  // "fileg_start_onccN",
  // "fileg_sustain",
  // "fileg_sustain_onccN",
  // "fileg_vel2sustain",
  "fillfo_delay",
  "fillfo_depth",
  // "fillfo_depthccN",
  "fillfo_depthchanaft",
  "fillfo_depthpolyaft",
  "fillfo_fade",
  "fillfo_freq",
  // "fillfo_freqccN",
  "fillfo_freqchanaft",
  "fillfo_freqpolyaft",
  "filter_cutoff",
  // "filter_cutoff_onccN",
  "filter_resonance",
  // "filter_resonance_onccN",
  "filter_type",
  // "fxNtomain",
  "fxNtomix",
  "gate_attack",
  // "gate_onccN",
  "gate_release",
  "gate_stlink",
  "gate_threshold",
  "global_amplitude",
  "global_label",
  "global_volume",
  "group",
  "group_amplitude",
  "group_label",
  "group_volume",
  "hibend",
  "hibpm",
  // "hiccN",
  // "hichan",
  "hichanaft",
  // "hihdccN",
  "hikey",
  "hint_*",
  "hipolyaft",
  "hiprog",
  "hirand",
  "hitimer",
  "hivel",
  "image",
  "internal",
  "key",
  // "label_ccN",
  /*
  "lfoN_amplitude",
  "lfoN_amplitude_onccX",
  "lfoN_amplitude_smoothccX",
  "lfoN_amplitude_stepccX",
  "lfoN_bitred",
  "lfoN_bitred_onccX",
  "lfoN_bitred_smoothccX",
  "lfoN_bitred_stepccX",
  "lfoN_count",
  "lfoN_cutoff",
  "lfoN_cutoff_onccX",
  "lfoN_cutoff_smoothccX",
  "lfoN_cutoff_stepccX",
  "lfoN_cutoff2",
  "lfoN_cutoff2_onccX",
  "lfoN_cutoff2_smoothccX",
  "lfoN_cutoff2_stepccX",
  "lfoN_decim",
  "lfoN_decim_onccX",
  "lfoN_decim_smoothccX",
  "lfoN_decim_stepccX",
  "lfoN_delay",
  "lfoN_delay_onccX",
  "lfoN_depth_lfoX",
  "lfoN_depthadd_lfoX",
  "lfoN_drive",
  "lfoN_drive_onccX",
  "lfoN_drive_smoothccX",
  "lfoN_drive_stepccX",
  "lfoN_eqXbw",
  "lfoN_eqXbw_onccY",
  "lfoN_eqXbw_smoothccY",
  "lfoN_eqXbw_stepccY",
  "lfoN_eqXfreq",
  "lfoN_eqXfreq_onccY",
  "lfoN_eqXfreq_smoothccY",
  "lfoN_eqXfreq_stepccY",
  // "lfoN_eqXgain",
  "lfoN_eqXgain_onccY",
  "lfoN_eqXgain_smoothccY",
  "lfoN_eqXgain_stepccY",
  "lfoN_fade",
  "lfoN_fade_onccX",
  "lfoN_freq",
  "lfoN_freq_onccX",
  "lfoN_freq_smoothccX",
  "lfoN_freq_stepccX",
  "lfoN_freq_lfoX",
  "lfoN_freq_lfoX_onccY",
  "lfoN_noiselevel",
  "lfoN_noiselevel_onccX",
  "lfoN_noiselevel_smoothccX",
  "lfoN_noiselevel_stepccX",
  "lfoN_noisestep",
  "lfoN_noisestep_onccX",
  "lfoN_noisestep_smoothccX",
  "lfoN_noisestep_stepccX",
  "lfoN_noisetone",
  "lfoN_noisetone_onccX",
  "lfoN_noisetone_smoothccX",
  "lfoN_noisetone_stepccX",
  "lfoN_offset",
  "lfoN_pan",
  "lfoN_pan_onccX",
  "lfoN_pan_smoothccX",
  "lfoN_pan_stepccX",
  "lfoN_phase",
  "lfoN_phase_onccX",
  "lfoN_pitch",
  "lfoN_pitch_curveccX",
  "lfoN_pitch_onccX",
  "lfoN_pitch_smoothccX",
  "lfoN_pitch_stepccX",
  "lfoN_ratio",
  "lfoN_resonance",
  "lfoN_resonance_onccX",
  "lfoN_resonance_smoothccX",
  "lfoN_resonance_stepccX",
  "lfoN_resonance2",
  "lfoN_resonance2_onccX",
  "lfoN_resonance2_smoothccX",
  "lfoN_resonance2_stepccX",
  "lfoN_scale",
  "lfoN_smooth",
  "lfoN_smooth_onccX",
  "lfoN_stepX",
  "lfoN_stepX_onccY",
  "lfoN_steps",
  "lfoN_volume",
  "lfoN_volume_onccX",
  "lfoN_volume_smoothccX",
  "lfoN_volume_stepccX",
  "lfoN_wave",
  "lfoN_wave_onccX",
  "lfoN_waveX",
  "lfoN_width",
  "lfoN_width_onccX",
  "lfoN_width_smoothccX",
  "lfoN_width_stepccX",
   */
  "load_end",
  "load_mode",
  "load_start",
  "lobend",
  "lobpm",
  // "loccN",
  "lochan",
  "lochanaft",
  // "lohdccN",
  "lokey",
  "loop_count",
  "loop_crossfade",
  "loop_end",
  "loop_mode",
  "loop_start",
  "loop_type",
  "lopolyaft",
  "loprog",
  "lorand",
  "lotimer",
  "lovel",
  "master_amplitude",
  "master_label",
  "master_volume",
  "md5",
  "noise_filter",
  "noise_level",
  // "noise_level_onccN",
  // "noise_level_smoothccN",
  "noise_step",
  // "noise_step_onccN",
  "noise_stereo",
  "noise_tone",
  // "noise_tone_onccN",
  "note_offset",
  "note_polyphony",
  "note_selfmask",
  "octave_offset",
  "off_by",
  "off_curve",
  "off_mode",
  "off_shape",
  "off_time",
  "offset",
  // "offset_ccN",
  "offset_random",
  // "on_hiccN",
  // "on_hihdccN",
  // "on_loccN",
  // "on_lohdccN",
  "oscillator",
  "oscillator_detune",
  // "oscillator_detune_onccN",
  "oscillator_mod_depth",
  // "oscillator_mod_depth_onccN",
  // "oscillator_mod_smoothccN",
  "oscillator_mode",
  "oscillator_multi",
  "oscillator_phase",
  "oscillator_quality",
  "oscillator_table_size",
  "output",
  // "pan",
  // "pan_onccN",
  // "pan_curveccN",
  // "pan_smoothccN",
  // "pan_stepccN",
  "pan_keycenter",
  "pan_keytrack",
  "pan_law",
  "pan_veltrack",
  "param_offset",
  "phase",
  "phaser_depth",
  // "phaser_depth_onccN",
  "phaser_feedback",
  // "phaser_feedback_onccN",
  "phaser_freq",
  // "phaser_freq_onccN",
  // "phaser_phase_onccN",
  "phaser_stages",
  "phaser_waveform",
  "phaser_wet",
  // "phaser_wet_onccN",
  "pitch",
  // "pitch_onccN",
  // "pitch_curveccN",
  // "pitch_smoothccN",
  // "pitch_stepccN",
  "pitch_keycenter",
  "pitch_keytrack",
  "pitch_random",
  "pitch_veltrack",
  "pitcheg_attack",
  // "pitcheg_attack_onccN",
  "pitcheg_vel2attack",
  "pitcheg_attack_shape",
  "pitcheg_decay",
  // "pitcheg_decay_onccN",
  "pitcheg_vel2decay",
  "pitcheg_decay_shape",
  "pitcheg_decay_zero",
  "pitcheg_delay",
  // "pitcheg_delay_onccN",
  "pitcheg_vel2delay",
  "pitcheg_depth",
  // "pitcheg_depth_onccN",
  "pitcheg_vel2depth",
  "pitcheg_dynamic",
  "pitcheg_hold",
  // "pitcheg_hold_onccN",
  "pitcheg_vel2hold",
  "pitcheg_release",
  // "pitcheg_release_onccN",
  "pitcheg_vel2release",
  "pitcheg_release_shape",
  "pitcheg_release_zero",
  "pitcheg_start",
  // "pitcheg_start_onccN",
  // "pitcheg_sustain",
  // "pitcheg_sustain_onccN",
  // "pitcheg_vel2sustain",
  "pitchlfo_delay",
  "pitchlfo_depth",
  // "pitchlfo_depthccN",
  "pitchlfo_depthchanaft",
  "pitchlfo_depthpolyaft",
  "pitchlfo_fade",
  "pitchlfo_freq",
  // "pitchlfo_freqccN",
  "pitchlfo_freqchanaft",
  "pitchlfo_freqpolyaft",
  "polyphony",
  "polyphony_group",
  "polyphony_stealing",
  // "position",
  "position_veltrack",
  "region_label",
  "resonance",
  // "resonance_onccN",
  // "resonance_curveccN",
  // "resonance_smoothccN",
  // "resonance_stepccN",
  "resonance2",
  // "resonance2_onccN",
  // "resonance2_curveccN",
  // "resonance2_smoothccN",
  // "resonance2_stepccN",
  "reverb_damp",
  // "reverb_damp_onccN",
  "reverb_dry",
  // "reverb_dry_onccN",
  "reverb_input",
  // "reverb_input_onccN",
  "reverb_predelay",
  // "reverb_predelay_onccN",
  "reverb_size",
  // "reverb_size_onccN",
  "reverb_tone",
  // "reverb_tone_onccN",
  "reverb_type",
  "reverb_wet",
  // "reverb_wet_onccN",
  // "reverse_hiccN",
  // "reverse_loccN",
  "rt_dead",
  "rt_decay",
  "sample",
  "sample_fadeout",
  "sample_quality",
  "script",
  "seq_length",
  // "seq_position",
  // "set_ccN",
  // "set_hdccN",
  "sostenuto_cc",
  "sostenuto_lo",
  "sostenuto_sw",
  // "start_hiccN",
  // "start_hihdccN",
  // "start_loccN",
  // "start_lohdccN",
  "static_cyclic_level",
  "static_cyclic_time",
  "static_filter",
  "static_level",
  // "static_level_onccN",
  "static_random_level",
  "static_random_maxtime",
  "static_random_mintime",
  "static_stereo",
  "static_tone",
  "stop_beats",
  // "stop_hiccN",
  // "stop_hihdccN",
  // "stop_loccN",
  // "stop_lohdccN",
  "strings_number",
  // "strings_wet_onccN",
  "sustain_cc",
  "sustain_lo",
  "sustain_sw",
  "sw_default",
  // "sw_down",
  "sw_hikey",
  "sw_hilast",
  "sw_label",
  "sw_last",
  "sw_lokey",
  "sw_lolast",
  "sw_note_offset",
  "sw_octave_offset",
  "sw_previous",
  "sw_up",
  "sw_vel",
  "sync_beats",
  "sync_offset",
  "tdfir_dry",
  // "tdfir_dry_onccN",
  // "tdfir_gain",
  "tdfir_impulse",
  "tdfir_wet",
  // "tdfir_wet_onccN",
  "transpose",
  "trigger",
  "tune",
  "type",
  // "	vN",
  "varNN_mod",
  "varNN_onccX",
  "varNN_curveccX",
  "varNN_target",
  "vendor_specific",
  "volume",
  // "gain_ccN",
  // "volume_curveccN",
  // "volume_smoothccN",
  // "volume_stepccN",
  "waveguide",
  "width",
  // "width_onccN",
  // "width_curveccN",
  // "width_smoothccN",
  // "width_stepccN",
  "xf_cccurve",
  "xf_keycurve",
  "xf_velcurve",
  // "xfin_hiccN",
  "xfin_hikey",
  "xfin_hivel",
  // "xfin_loccN",
  "xfin_lokey",
  "xfin_lovel",
  // "xfout_hiccN",
  "xfout_hikey",
  "xfout_hivel",
  // "xfout_loccN",
  "xfout_lokey",
  "xfout_lovel"]